# Generated by Django 2.0.5 on 2018-08-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
    ]
