# Generated by Django 2.0.5 on 2018-08-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_auto_20180806_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
    ]
