# Generated by Django 2.0.5 on 2018-08-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_auto_20180807_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='position',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='staff_status',
        ),
    ]
